// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.09/03       [395523]
Creator        : pseyfert
Date           : Sat May 13 17:20:12 2017
Host           : Linux hltperf-quanta01-e52630v4.lbdaq.cern.ch 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/pseyfert/root.install/tutorials/tmva
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.14423561096,7.26972866058]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-3.96643972397,4.0258936882]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.03730010986,4.27845287323]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.95050764084,4.64035463333]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.91655540466,8.67800140381]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.874833107,13.0170021057]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>


class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][4];
   double fMax_1[3][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[10][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][10];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 5; fWeights[0] = new double[5]; 
   fLayerSize[1] = 10; fWeights[1] = new double[10]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.440125203043803;
   fWeightMatrix0to1[1][0] = 2.05118334940934;
   fWeightMatrix0to1[2][0] = 0.810981629880295;
   fWeightMatrix0to1[3][0] = -0.19524720082245;
   fWeightMatrix0to1[4][0] = -5.04144504895303;
   fWeightMatrix0to1[5][0] = -2.79080283899066;
   fWeightMatrix0to1[6][0] = -0.8125538158976;
   fWeightMatrix0to1[7][0] = 3.67059861599944;
   fWeightMatrix0to1[8][0] = -1.61581142481164;
   fWeightMatrix0to1[0][1] = -2.11228268185487;
   fWeightMatrix0to1[1][1] = -1.49551455310798;
   fWeightMatrix0to1[2][1] = -0.542763851549404;
   fWeightMatrix0to1[3][1] = -2.38325478003271;
   fWeightMatrix0to1[4][1] = -0.53128484127359;
   fWeightMatrix0to1[5][1] = -0.28493615992531;
   fWeightMatrix0to1[6][1] = 0.34444903066759;
   fWeightMatrix0to1[7][1] = -0.0584700891022878;
   fWeightMatrix0to1[8][1] = 1.92497086890616;
   fWeightMatrix0to1[0][2] = -0.0845175738203556;
   fWeightMatrix0to1[1][2] = 1.41719302200466;
   fWeightMatrix0to1[2][2] = -0.213822653789018;
   fWeightMatrix0to1[3][2] = -0.888423544374853;
   fWeightMatrix0to1[4][2] = -1.9642197017187;
   fWeightMatrix0to1[5][2] = -0.549690425992514;
   fWeightMatrix0to1[6][2] = -0.960867329960204;
   fWeightMatrix0to1[7][2] = 0.768942749631942;
   fWeightMatrix0to1[8][2] = 0.725161902310138;
   fWeightMatrix0to1[0][3] = -4.48892875426137;
   fWeightMatrix0to1[1][3] = -1.67286398816664;
   fWeightMatrix0to1[2][3] = 0.691648243170984;
   fWeightMatrix0to1[3][3] = 3.57276784261435;
   fWeightMatrix0to1[4][3] = 7.14376065683792;
   fWeightMatrix0to1[5][3] = 3.27071668356127;
   fWeightMatrix0to1[6][3] = 0.522908438641061;
   fWeightMatrix0to1[7][3] = -1.514450365434;
   fWeightMatrix0to1[8][3] = 1.24680531700746;
   fWeightMatrix0to1[0][4] = 0.287127125984557;
   fWeightMatrix0to1[1][4] = 1.97386249468041;
   fWeightMatrix0to1[2][4] = -0.0661316136889917;
   fWeightMatrix0to1[3][4] = -0.783295815051551;
   fWeightMatrix0to1[4][4] = -0.708121991776393;
   fWeightMatrix0to1[5][4] = 0.0802716277015281;
   fWeightMatrix0to1[6][4] = 1.85708425275543;
   fWeightMatrix0to1[7][4] = -0.0806033927599458;
   fWeightMatrix0to1[8][4] = -1.39805232600936;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.57726039443935;
   fWeightMatrix1to2[0][1] = 0.297137209568078;
   fWeightMatrix1to2[0][2] = 0.386784471429434;
   fWeightMatrix1to2[0][3] = 1.78354550943198;
   fWeightMatrix1to2[0][4] = 2.89134080608428;
   fWeightMatrix1to2[0][5] = 1.7368767288619;
   fWeightMatrix1to2[0][6] = 1.47392101562946;
   fWeightMatrix1to2[0][7] = -1.27837704673456;
   fWeightMatrix1to2[0][8] = 0.831335568171545;
   fWeightMatrix1to2[0][9] = -1.48568537085098;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -4.94358778;
   fMax_1[0][0] = 6.3994679451;
   fMin_1[1][0] = -8.14423561096;
   fMax_1[1][0] = 7.26972866058;
   fMin_1[2][0] = -8.14423561096;
   fMax_1[2][0] = 7.26972866058;
   fMin_1[0][1] = -3.96643972397;
   fMax_1[0][1] = 3.11266636848;
   fMin_1[1][1] = -3.25508260727;
   fMax_1[1][1] = 4.0258936882;
   fMin_1[2][1] = -3.96643972397;
   fMax_1[2][1] = 4.0258936882;
   fMin_1[0][2] = -2.78645992279;
   fMax_1[0][2] = 3.50111722946;
   fMin_1[1][2] = -5.03730010986;
   fMax_1[1][2] = 4.27845287323;
   fMin_1[2][2] = -5.03730010986;
   fMax_1[2][2] = 4.27845287323;
   fMin_1[0][3] = -2.42712664604;
   fMax_1[0][3] = 4.5351858139;
   fMin_1[1][3] = -5.95050764084;
   fMax_1[1][3] = 4.64035463333;
   fMin_1[2][3] = -5.95050764084;
   fMax_1[2][3] = 4.64035463333;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 4;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<4;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
